name: Tests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 9009
          container port: 9008
          mysql user: user
          mysql password: 123
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run phpunit
        env:
          DB_USER: user
          DB_PASSWD: 123
          DB_DSN: mysql:host=localhost;port=9009
        run: vendor/bin/phpunit